# Site settings
title: Cerebrate with Shubham
description: "A blog with a new take on software processes and tools"
url: "https://shubhamkumarsaxena.github.io/blog/"
author:
  name: "Shubham Kumar"
  email: "shubham.kumar@gmail.com"
  url: "https://shubhamkumarsaxena.github.io/blog/"

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
